version: "3.7"

services:
  clean-arch:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      spring_data_mongodb_host: mongo
    ports:
      - 8080:8080
      - 8081:8081
    image: clean-arch
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

volumes:
  data: